version: '3.1'
services:
  web:
    container_name: odoo18_portal_payment
    image: odoo:18
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      -  odoo-web-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
  db:
    container_name: db_odoo
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
